### ISSUE TITLE
Constrain an Entity to the centre of navmesh regions

### ISSUE THREAD

**Issue by Coder2012** [Mugen87/yuka#10]
When using `navmesh.findPath(from, to)`, the resulting path will hit the edges of poligons so that it is the shortest path possible.

When using this with a `clampMovement`, the Entity can collide with the wall and slow down while it slides along.

How could we ensure the Entity stays away from the walls (maybe in the centre of each region) so that it doesn't collide?

**Comment by Mugen87** [comment]
You normally use a "follow path" steering behavior that will move the game entity along the given path. This is actually demonstrated in both navmesh demos:

https://mugen87.github.io/yuka/examples/navigation/navmesh/
https://mugen87.github.io/yuka/examples/navigation/navmeshPerformance/

`NavMesh.clampMovement()` is should not be necessary when a game entity follows a path. It can be used to restrict the movement of the player or in situations where the game entity does not follow a path but moves more freely (e.g. during combat).

**Comment by Coder2012** [comment]
Yes I see the follow path examples, but as I pointed out the first demo `navigation/navmesh` you can see when it creates the path the red line will hit the corners of a region, how can we avoid this?

**Comment by Mugen87** [comment]
> the red line will hit the corners of a region

Okay, I see what you mean. Right now, it's not possible to solve this issue with the existing logic. As you mentioned before, `NavMesh` returns the shortest possible path which means it goes past the corners of a nav mesh. 

However, keep in mind that a navigation mesh is always smaller than the actual level geometry. A nav mesh generator usually respects a defined bounding radius of game entities which ensures they never touch the walls of the level.

We could also consider to enhance `NavMesh` in order to return a different type of path. It would not be the shortest one since it would go exactly through the mid point of all portal edges. You could then use the normal follow path behavior to achieve your intended result. Unfortunately, I don't know how common such a path is. In general, we try to focus on established best practices so it seems we need some additional investigation here. It would be good to know how devs solves this issue with other game engines.

**Comment by Coder2012** [comment]
I think your suggestion of using the mid point of all portal edges sounds interesting.

Maybe my case is less common, I'm using corridors and would like a robot stay in the centre of these, maybe a thinner navmesh would suffice for now.

**Comment by Glidias** [comment]
You could always set up your own A-star (or other) Search instance https://github.com/Mugen87/yuka/tree/master/src/graph/search  and execute it on the `navmesh.graph` itself and do whatever you think is most optimized for your game  (I actually think this is better since you can always use search.clear() instead of it re-creating a new search instance each time based off the default navmesh implementation.). With that, you get the list of navmesh polygon regions you need to pass through....so, you if ou don't like the corner hugging environment, you can use your own method of path creation. 

On my personal fork branches i actually have Navmesh flags that allow disabling merging polygons and disabling graph creation, ie. if  I happen to decide to use a different graph costing/formatino system (eg. edge to edge...), or use Navmesh for different purposes outside of the usual case. 

I also use a flowfield algorithm based off a paper in http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.68.875&rep=rep1&type=pdf but  adapted it to support multiple agents flocking together with the help of Yuka behaviours along with my own seperate collision clippings to ensure the don't fall off the world. The result allows the AI (or robot), to steeer smoothly throught the corridoor via flowfield approach.  I actually left out the part in the paper (probably yagni) which involves splitting navmesh polygons at sharp corners to smoothen out movement with less overshooting, but overall it doesn't appear to make much of a noticable difference.

https://playcanv.as/b/wzjwonE5/

Some links on my Yuka navmesh flowfield implementations
https://github.com/Glidias/yuka/tree/personal/src/navigation/navmesh/flowfield
https://github.com/Glidias/yuka/issues/1

On the roadmap next for Yuka navmesh is,, (given input world 3D geometry/occluders), to have a set up Navmesh region/tiles/grid precomputed  visibility graph system. (To facilitate easy fog of war updates and fast O(1) constant visibility/potential occlusion queries between navmesh agents). I'd use this to optimize and skip the need to raycast or use expensive percentage exposure area calculations between agents across  the map unless absolutely necessary, (by knowing what navmesh regions are visible from where and which aren't), therefore optimizing the number of agent to agent queries i can make per frame. The convex hull classes and such in Yuka is proving useful in precomputing these visibility stuffs, actually.

**Comment by Mugen87** [comment]
Closing for now. I did not find an example where the path goes through the portal edges's center points. Of course it would be better to have a configurable solution but we try to focus the library on the most important use cases. As mentioned by @Glidias, you can perform the search yourself and then decide what to do with the corridor. It requires some study of `NavMesh` but I think it should be appropriate as a workaround.

**Comment by Glidias** [comment]
A good article here https://www.cs.upc.edu/~npelechano/CAG2014_Clearance.pdf just  for reference, should be fairly easy to implement with the current halfedge data structure and the yuka waypoint/flocking behaviours.
