### ISSUE TITLE
Agent avoids Meshes

### ISSUE THREAD

**Issue by YuryKonvpalto** [Mugen87/yuka#27]
Hi and thanx a lot for a great library!
Is it possible for agents (e.g. PursuitBehavior) to avoid meshes (boxes) by pursuing - like ObstAvoidanceBehavior, - but without marking the obstacles as GameEntities? E.g. a lot of trees/boxes. 
How would you implement it?

**Comment by Mugen87** [comment]
It's really hard to give you an advice without more information about your use case.

Anyway, if you have a lots of trees or other static objects in your game world, I suggest you use a navigation mesh which provide you a navigation path through the obstacles. In this way, you can use the simple `FollowPath` behavior and don't rely on more complex steering behaviors which can fail pretty fast depending on your use case.

**Comment by YuryKonvpalto** [comment]
What I ve meant is just simple plane with say 10 boxes/meshes scattered on top of it. There are an agent with Pursuitbehavior and an evader - real player. An agent and an avader are playing simple "catch up".
The question is - is there any trick or a tip how an agent would take into consideration the boxes while making a pursuit for an evader-player?
So looks like a FollowPath would not do in this case (evader-realplayer moves randomly), or would it somehow?

**Comment by Mugen87** [comment]
> So looks like a FollowPath would not do in this case (evader-realplayer moves randomly), or would it somehow?

No not really. `FollowPath` just moves along a navigation path and that's it. However, you can try to predict the target position according to the player's movement before requesting the navigation path which will make the entity's movement smarter again. 

If you just use a combination of `PursuitBehavior` and `ObstacleAvoidanceBehavior`, it really depends on the specific use case whether the result is appropriate or not. If the obstacle are not too big (let's say they have the size of the player), I would start with this approach and see how it goes. If the result is not satisfying, I would compute a target position which takes into account the player's movement and then use a navigation path. However, this only works if the obstacles are static. Otherwise the nav mesh does not reflect the game world.

**Comment by YuryKonvpalto** [comment]
Ok, I'll try that approach with a FollowPath; may be it will do.. I plan to put a Cannon.js body into obstacles-boxes (they could be easily moved) and try to synchronize an agent with cannon-body too. Let see where it'll lead to..
Thanx a lot for advice!

**Comment by Mugen87** [comment]
> Let see where it'll lead to..

Please share the result if the game is ready! I would love to see how your solution works.
