### ISSUE TITLE
Integrate with collision/physics engine?

### ISSUE THREAD

**Issue by Glidias** [Mugen87/yuka#4]
Anyway of integrating flocking and various entity behaviours with any given collision/physics  engine/solver? Also, what about integrating with NAvmesh ClampMovement + among agent radius itself. Would probably require after entityManager.update() to set to this.velocity to some physics force (maybe even save prevPosition before entityManager.update(), then update entity positions again based off physics engine's entities instead? (to cancel away default `this.position.copy( target );`)

**Comment by Mugen87** [comment]
> Anyway of integrating flocking and various entity behaviours with any given collision/physics engine/solver? 

Unfortunately no. Yuka was developed without the idea of utilizing a separate physics engine. In general, we try to avoid the overhead of a physics engine in our apps and implement collision and intersection tests by ourselves with basic math entities. 

However, that does not mean the project refuses a possible enhancement to `EntityManager` or `GameEnity` in order to realize the integration of a physics engine. But we have to ensure that the API (maybe just a new callback function) is generic and other stuff of the library does not break if a physics simulation is active. It might be hard to achieve this without some serious refactoring...

**Comment by Glidias** [comment]
I tried it with  Box2D-like physics engine...and simply updating the Vehicles' positions (based off physics engine bodies' position..), before calling `entityManager.update(dt)`, and simply `setLinearVelocity(vehicle.velocity)` on all respective physics bodies after updating entities before calling `yourPhysicsEngine.update(dt)` appears to work fine. I guess as long as as the flocking/AI behaviours don't rely on/exploit  any frame coherant info (is there any?), for previous frames, it should be fine.  But it's true that with this method:  the MovingEntity/Vehicle lines  for position.copy() and displacement.copy() is made redundant.

Btw, i'm thinking of implementing my own navmesh agent flowfield behaviour with this framework.... Here's how i think i'm going to do it: https://gingkoapp.com/how-to-gridless-rts

**Comment by Mugen87** [comment]
Interesting! Will your code be Open-Source?^^

**Comment by Glidias** [comment]
It will be under the `personal` branch on my fork

**Comment by Glidias** [comment]
Regarding getPortalEdgeTo(), i noticed the left/right assignments appear to be .prev.vertex and .vertex respesctively. Does htis mean that the left/right refers to the dirction relative to  being outside the polygon instead of being inside? I'm kind of onfused by the convention with regards to what is "left"/"right" for portal edge data structure as it appears to be flipped in the other way if you consider "left" as "left from inside the polygon".

**Comment by Mugen87** [comment]
Yes, the current nomenclature is a bit confusing. The edges of a polygon are defined in CCW order where `HalfEdge.vertex` represents the head or destination vertex of the respective (full) edge.  So considering you are standing inside the polygon and look outside, the left/right vertices of a portal edge are twisted. It's correct if you look from outside the polygon onto the edge.

When I remember correctly we did this because the algorithm in `Corridor` expects this kind of definition. If you change the code in `Polygon.getPortalEdgeTo()`  to
```js
portalEdge.left = edge.vertex;
portalEdge.right = edge.prev.vertex;
```
the result of `Corridor` is not correct anymore. So this class needs a fix to.

**Comment by Glidias** [comment]
> Interesting! Will your code be Open-Source?^^

YOu can check out a wip demo of what i've done so far with NavMeshFlowFieldBehaviour
https://github.com/Glidias/yuka/issues/1

It's still in testing/checking stages so the `personal` branch code is loaded with console traces.
