### ISSUE TITLE
WanderBehavior within Navmesh

### ISSUE THREAD

**Issue by YuryKonvpalto** [Mugen87/yuka#41]
Hi Guys!,

Is it possible to apply a e.g. WanderBehavior within a NavMesh? - I mean a vehicle would wander aimlessly within bounds of a NavMesh?
Or one can use only pathes in Navmesh?

**Comment by Mugen87** [comment]
You can combine both but the bounds check is not something that happens automatically. Meaning you have to use [NavMesh.clampMovement()](https://mugen87.github.io/yuka/docs/NavMesh.html#clampMovement) so the game entity does not leave the nav mesh.

Notice that this approach potentially produces odd results since the wander behavior might steer the entity into a direction which leads off the nav mesh. Normally you would expect the behavior changes the direction if a boundary is going to be hit. So it might be better to create a custom steering behavior for this use case.

**Comment by YuryKonvpalto** [comment]
Thanks a lot!
