### ISSUE TITLE
Polygon.getPortalEdge left/right confusion

### ISSUE THREAD

**Issue by Glidias** [Mugen87/yuka#5]
Regarding getPortalEdgeTo(), i noticed the left/right assignments appear to be .prev.vertex and .vertex respesctively. Does htis mean that the left/right refers to the dirction relative to  being outside the polygon instead of being inside? I'm kind of onfused by the convention with regards to what is "left"/"right" for portal edge data structure as it appears to be flipped in the other way if you consider "left" as "left from inside the polygon".  Since polygon edges are winded counter-clockwise, it doesn't appear to make sense if "left" is {left:this.prev.vertex} when "right" should alawys refer to previous vertex since counter-clockwise motion goes from right to left...., (and if using right hand convention along flow direction, it's asssumed the polygon normals should point inwards?)

Perhaps, you should document about the portal data structure and what is "right"/"left" exactly according to certain conventions and make it consistent.

Additionally, maybe getPortalEdgeTo is not very useful generally, and maybe it should just be something more generic like getEdgeTo():HalfEdge, since it appears getPortalEdgeTo is only used by Navmesh and may be better off being used within NavMesh class only instead.

I suspect, assuming you are refering to the old post code from dijesting duck, maybe he had it as if the polygons were wounded clockwise so you deliberately flipped it on purpose to get it to work?

**Comment by Mugen87** [comment]
Yes, the current nomenclature is a bit confusing. The edges of a polygon are defined in CCW order where `HalfEdge.vertex` represents the head or destination vertex of the respective (full) edge.  So considering you are standing inside the polygon and look outside, the left/right vertices of a portal edge are twisted. It's correct if you look from outside the polygon onto the edge.

When I remember correctly we did this because the algorithm in `Corridor` expects this kind of definition. If you change the code in `Polygon.getPortalEdgeTo()`  to
```js
portalEdge.left = edge.vertex;
portalEdge.right = edge.prev.vertex;
```
the result of `Corridor` is not correct anymore. So this class needs a fix too.

**Comment by Mugen87** [comment]
> Right now, it seems shifting the method to NavMesh is the most clear solution.

Done! 91f7367ca010edce1024e4696015cc774970d734

**Comment by Mugen87** [comment]
>  Perhaps, you should document about the portal data structure and what is "right"/"left" exactly according to certain conventions and make it consistent.

Added some comments via 774d48c91cdb1fc2c3263abe4fcfd9dd4938868a. Things should be hopefully more clear now.

**Comment by Mugen87** [comment]
@Glidias Thanks for your valuable feedback! 👍
