### ISSUE TITLE
Spatial search and shortest path need to make a grid in advance in 3D modeling software

### ISSUE THREAD

**Issue by WREQI** [Mugen87/yuka#6]
Ask a question, as shown in Figure I get the coordinates of the two points to connect them together, but this is very troublesome, I think if you can use the AI ​​space search to make the line around the obstacles, connect together according to certain restrictions, you can?

**Comment by Mugen87** [comment]
TBH, you formulation is a bit vague so I'm not sure what I should answer to your question. Yes, it is possible to use e.g. navigation graphs in order to find the shortest path between two points without intersection obstacles. However, you need special data structures for this. If you are not familiar with this stuff, I highly recommend to do some research and study first.
